version: '3.0'

services:
  webserver:
    image: ylked/php8-composer
    container_name: p1-server
    ports: 
      - 8000:8000
    volumes:
      - ../src:/var/www/html
      - ../../project-1:/files
      - ./log:/var/log/apache2
    working_dir: /files/p1
    command: ["/usr/bin/php", "artisan", "serve", "--host", "0.0.0.0"]

  db:
    image: mariadb
    container_name: p1-db
    ports:
      - 3306:3306
        
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "default"
      MYSQL_USER: "ylked"
      MYSQL_PASSWORD: "pass"
        
  adminer:
    image: adminer
    container_name: p1-adminer

    ports:
      - 8080:8080

